export const ROUTING_ENUM = {
    trophies: "/trophies",
    pastChampions: "/past-champions",
    management: "/management",
    statue: "/statue",
    createGame: "/create-game",
    gameTables: "/game-tables",
    roundsChampions: "/rounds-champions",
    polishOpen: "/polish-open",
    fifaWorldCup: "/fifa-world-cup",
    playerProfiles: "/player-profiles",
    list: "/list",
    recordsFifa: "/records-fifa",
    leaugeStatue: "/leauge-statue",
    polishOpenStatue: "/polish-open-statue",
    gallery: "/gallery",
    contact: "/contact",
    polishFields: "/polish-fields",
    auth: "/auth"
}